apiVersion: apps/v1
kind: Deployment
metadata:
  name: platforms-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: platformservice
  template:
    metadata:
      labels:
        app: platformservice
    spec:
      containers:
        - name: platformservice
          image: skelevel/platformservice:v1.0.2
 

